version: "3.8"
services:
  grafana:
    image: "grafana/grafana"
    volumes:
      - "data:/var/lib/grafana"
    ports:
      - "192.168.100.1:3000:3000"
    restart: "unless-stopped"
volumes:
  data: {}
