version: "3.8"
services:
  influxdb:
    image: "influxdb"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_HTTP_LOG_ENABLED: "false"
    volumes:
      - "data:/var/lib/influxdb"
      - "./initdb:/docker-entrypoint-initdb.d"
    ports:
      - "192.168.100.1:8086:8086"
    restart: "unless-stopped"
volumes:
  data: {}
