{
 "title": "Desktop",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "coretemp_packageid0_input" }
     ]
    },
    {
     "alias": "gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "temperature_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GeForce GTX 1060 6GB" }
     ]
    },
    {
     "alias": "ssd0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "ssd1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "hdd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "wifi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "iwlwifi_1_input" }
     ]
    },
    {
     "alias": "cpu_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "coretemp_packageid0_input" }
     ]
    },
    {
     "alias": "gpu_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "temperature_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GeForce GTX 1060 6GB" }
     ]
    },
    {
     "alias": "ssd0_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "ssd1_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "hdd_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "wifi_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "iwlwifi_1_input" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "power_draw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GeForce GTX 1060 6GB" }
     ]
    },
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "Cores frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_freq",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "guest_nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "softirq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "load5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "load1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "CPU memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "GPU memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "Intel Ethernet I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eno2" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eno2" }
     ]
    }
   ]
  },
  {
   "title": "Realtek Ethernet I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "enp4s0" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "enp4s0" }
     ]
    }
   ]
  },
  {
   "title": "WiFi I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlo1" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlo1" }
     ]
    }
   ]
  },
  {
   "title": "WiFi link quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "link quality",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless",
     "query": "SELECT mean(\"link\") FROM \"wireless\" WHERE (\"host\" = 'desktop' AND \"interface\" = 'wlo1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlo1" }
     ]
    },
    {
     "alias": "link quality_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless",
     "query": "SELECT mean(\"link\") FROM \"wireless\" WHERE (\"host\" = 'desktop' AND \"interface\" = 'wlo1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlo1" }
     ]
    }
   ]
  },
  {
   "title": "SSD1 I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "S466NB0K412967V" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "S466NB0K412967V" }
     ]
    }
   ]
  },
  {
   "title": "HDD I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "WDZKNXGD" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "WDZKNXGD" }
     ]
    }
   ]
  },
  {
   "title": "/ usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "/data usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "SSD0 TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Written" }
     ]
    }
   ]
  },
  {
   "title": "SSD1 TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Written" }
     ]
    }
   ]
  },
  {
   "title": "HDD TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Total_LBAs_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Total_LBAs_Written" }
     ]
    }
   ]
  },
  {
   "title": "Mouse battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "razer",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "PM2035H15804385" }
     ]
    }
   ]
  }
 ]
}