{
 "title": "Desktop (win10)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "cpu_core",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core" }
     ]
    },
    {
     "alias": "cpu_package",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Package" }
     ]
    },
    {
     "alias": "gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GPU Core" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "cpu_core",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Power" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Cores" }
     ]
    },
    {
     "alias": "cpu_package",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Power" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Package" }
     ]
    },
    {
     "alias": "gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Power" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GPU Power" }
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "+12V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Voltage" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Voltage #5" }
     ]
    },
    {
     "alias": "+5V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Voltage" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Voltage #2" }
     ]
    },
    {
     "alias": "+3.3V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Voltage" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "3VCC" }
     ]
    }
   ]
  },
  {
   "title": "Cores frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "alias": "core0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #1" }
     ]
    },
    {
     "alias": "core1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #2" }
     ]
    },
    {
     "alias": "core2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #3" }
     ]
    },
    {
     "alias": "core3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #4" }
     ]
    },
    {
     "alias": "core4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #5" }
     ]
    },
    {
     "alias": "core5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Clock" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CPU Core #6" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100-mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" = 'desktop-win10' AND \"instance\" = '_Total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    },
    {
     "alias": "privileged",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100-mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" = 'desktop-win10' AND \"instance\" = '_Total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT 100-mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" = 'desktop-win10' AND \"instance\" = '_Total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "CPU memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "query": "SELECT 34359738368-mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"host\" = 'desktop-win10') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Data" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Used Memory" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "query": "SELECT 34359738368-mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"host\" = 'desktop-win10') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Data" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Available Memory" }
     ]
    }
   ]
  },
  {
   "title": "GPU memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "SmallData" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GPU Memory Used" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openhardwaremonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "SmallData" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "GPU Memory Free" }
     ]
    }
   ]
  },
  {
   "title": "Intel Ethernet I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] Ethernet Connection [7] I219-V"
      }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] Ethernet Connection [7] I219-V"
      }
     ]
    }
   ]
  },
  {
   "title": "Realtek Ethernet I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Realtek PCIe GbE Family Controller"
      }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Realtek PCIe GbE Family Controller"
      }
     ]
    }
   ]
  },
  {
   "title": "WiFi I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] Wireless-AC 9560 160MHz"
      }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] Wireless-AC 9560 160MHz"
      }
     ]
    }
   ]
  },
  {
   "title": "SSD I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") FROM \"win_diskio\" WHERE (\"host\" = 'desktop-win10' AND \"instance\" = '1 C:') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "1 C:" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") FROM \"win_diskio\" WHERE (\"host\" = 'desktop-win10' AND \"instance\" = '1 C:') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "1 C:" }
     ]
    }
   ]
  }
 ]
}