{
 "title": "Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "C:\\ usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop-win10" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
     ]
    }
   ]
  },
  {
   "title": "/ usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "/data usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "SSD0 TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Written" }
     ]
    }
   ]
  },
  {
   "title": "SSD1 TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Data_Units_Written" }
     ]
    }
   ]
  },
  {
   "title": "HDD TBR / TBW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "tbr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Total_LBAs_Read" }
     ]
    },
    {
     "alias": "tbw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*512" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "ST2000LX001-1RG174" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "WDZKNXGD" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Total_LBAs_Written" }
     ]
    }
   ]
  }
 ]
}